### PR TITLE
Updated Movie Row Component

### LINKED ISSUE #33: Update MovieRow Component
Currently MovieRow component renders a trivial JSX. It should render a table with 2 columns, one for the movie-poster and another containing 2 row each, the top one for movie-title and bottom for short description of the movie.

### PR DESCRIPTION
**Pull request by JLodha**
__33__ 

Fixes #33 

#### Short description of what this resolves:
Added table to store the movie details as per the requirement

#### Changes proposed in this pull request and/or Screenshots of changes:

-Changes done is MovieRow.js file located in src folder
-
-

### CODE REVIEW

**Comment by niftyy** [comment]
fix the indentation.

**Comment by JLodha** [comment]
Sir please have a look.
Thanks

**Comment by niftyy** [comment]
still not good enough, and inner table tag is not closed.

**Comment by JLodha** [comment]
What do you mean by proper indentation, sir?
I closed the inner table tag :P

**Comment by niftyy** [comment]
Screenshot 2020-01-19 at 10 11 22 AM

**Comment by JLodha** [comment]
Sir i closed the inner table tag on my local machine  will push it after correcting the indentation.
Please tell me what should i do to correct the indentation
Thank you

**Comment by niftyy** [comment]
For this project I want you to use tabsize: 4. Opening and closing tags __MUST__ be aligned. There should be a single space before opening a parenthesis and a semicolon after closing it. There should be no extra whitespaces. Look at the previous screenshot as an example. If you are on VS Code, you can use the Extension called Prettier to get the job done automatically. Don't forget to merge all commits into one.

**Comment by JLodha** [comment]
-

**Pull request closed without merging**
