### PR TITLE
Replaced props with movie object

### LINKED ISSUE #75: replace props with movie object
Currently individual key-value pairs are being passed as props to rows, replace them with movie object.

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__75__ 

Fixes #75

#### Short description of what this resolves:

Replaced props with movie object

#### Changes proposed in this pull request and/or Screenshots of changes:

underground

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
@niftyy please review

**Comment by niftyy** [comment]
instead of individually passing each prop (eg. moviename, poster etc.) you need to update the props passed to each movierow, what you have done is pushed movie object into the array instead.

**Comment by untrulynoxiusmj** [comment]
sir, but the issue said "replace props with movie object"

**Comment by niftyy** [comment]
what I meant is to replace the properties (movie.title, movie.overview etc) to be replaced by a single property movie (object) that would contain all of it.

**Comment by untrulynoxiusmj** [comment]
so i need to make a new movie object having only title , overview etc. as property and push that into the array ?

**Comment by niftyy** [comment]
you already have movie object as results[i], you just need to update the mRow object with the properties/props replaced as mentioned above.

**Comment by untrulynoxiusmj** [comment]
@niftyy is it correct now?

**Comment by niftyy** [comment]
you don't have to create new movie object, it is already present as 'let movie'.

**Comment by niftyy** [comment]
squash the commits

**Pull request merged**
