### PR TITLE
screensshot added

### PR DESCRIPTION
**Pull request by garvitchittora**
__7__ 

#### Short description of what this resolves:
screenshot added

#### Changes proposed in this pull request and/or Screenshots of changes:
garvitchittora

-
-

### CODE REVIEW

**Comment by niftyy** [comment]
follow the naming instruction and remove fixes #

**Comment by garvitchittora** [comment]
sir , done .

**Comment by niftyy** [comment]
@garvitchittora follow the screenshot naming instruction provided.

**Comment by garvitchittora** [comment]
done

**Pull request merged**
