### PR TITLE
Preloader added

### LINKED ISSUE #49: Add a preloader

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__49__ 

Fixes #49

#### Short description of what this resolves:

Added preloader

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
Sir, please check it

**Comment by niftyy** [comment]
squash all commits into one

**Comment by untrulynoxiusmj** [comment]
Sir, the second commit was done by me to resolve merge conflicts which occured due to some pull request merged
So i resolved that in second commit

**Comment by niftyy** [comment]
that is cool but you are allowed only once commit in a PR so you have to squash all of them into one

**Comment by untrulynoxiusmj** [comment]
Ok sir

**Comment by untrulynoxiusmj** [comment]
sir in original project 
code in app.css is like this
original
 so when i sync my fork it shows error in app.css
error
So now i have to correct it like 
correct
So now i squashed my commits
but due to this thing it again shows merge conflicts

**Comment by untrulynoxiusmj** [comment]
i think 
original
has an error in main project

**Comment by untrulynoxiusmj** [comment]
Sir , preloader looka like :
https://drive.google.com/file/d/1Mdfa0WmZH1cTYyLGZbgVFUHlb_y9F_mu/view

**Comment by niftyy** [comment]
great ! open a new issue if you think there's an error and send a PR with screenshot of it in a new folder called bugs. For this issue squash all the commits and I'll merge it.

**Comment by untrulynoxiusmj** [comment]
Sir, I have squashed all commits into one 
due to the above error pointed, it again shows conflicts

**Comment by untrulynoxiusmj** [comment]
I have corrected the error in this squashed commit

**Comment by niftyy** [comment]
there are merge conflicts

**Comment by untrulynoxiusmj** [comment]
er

**Comment by untrulynoxiusmj** [comment]
it shows this when i open (**Resolve conflicts**)

**Comment by untrulynoxiusmj** [comment]
Please tell me what to do

**Comment by niftyy** [comment]
https://www.youtube.com/watch?v=JtIX3HJKwfo

**Comment by untrulynoxiusmj** [comment]
it's done, sir

**Comment by niftyy** [comment]
squash again

**Comment by untrulynoxiusmj** [comment]
sir how to squash commits done by resolving conflicts
they don't appear when i try to squash
sq

**Comment by niftyy** [comment]
okay leave it for now

**Pull request merged**
