### PR TITLE
added a preloader

### LINKED ISSUE #49: Add a preloader

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__49__ 

Fixes #49

#### Short description of what this resolves:

added a preloader

### CODE REVIEW

**Comment by niftyy** [comment]
there are unnecessary commits present in this PR.

**Comment by untrulynoxiusmj** [comment]
Sir, can u explain how to manage those unnecessary commits ?

**Comment by niftyy** [comment]
update your fork or fork again and then make the required changes only.

**Comment by untrulynoxiusmj** [comment]
Sir please check it now 
I synced my fork and made pr

**Comment by untrulynoxiusmj** [comment]
Sir please check it now
I synced my fork

**Comment by niftyy** [comment]
still not working, there are 5 commits in this PR, first 2 of which are irrelevant.

**Comment by untrulynoxiusmj** [comment]
sir they are previous commits which have been merged

**Comment by niftyy** [comment]
they are not supposed to be in this PR regardless of whether they are merged or not, this particular issue is concerned with preloader only, and hence there should be only one commit for the same.

**Comment by untrulynoxiusmj** [comment]
should i make a new pr ?

**Comment by niftyy** [comment]
yes make a new pr with one relevant  commit only.

**Pull request closed without merging**
