### PR TITLE
website setup

### PR DESCRIPTION
**Pull request by harsh-8989**
__7__ 

issue #7 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by niftyy** [comment]
remove screenshot from the description and follow the PR template

**Comment by harsh-8989** [comment]
now it's ok!

**Comment by niftyy** [comment]
you don't have to write fixes on an 'Everyone' labeled issue and you have to use a '-' in the screenshot name rather than a '_'

**Comment by harsh-8989** [comment]
sir done!!

**Comment by niftyy** [comment]
great !

**Pull request merged**
