### PR TITLE
AJAX call to the API

### LINKED ISSUE #24: Make an AJAX call to the API
Make an AJAX call to the API in the performSearch Method and log the response on console.

### PR DESCRIPTION
**Pull request by JLodha**
__24__ 

Fixes #24 

#### Short description of what this resolves:
In the performSearch function in app.js i implemented a AJAX call to the api which returns the response to the console otherwise returns error.

#### Changes proposed in this pull request and/or Screenshots of changes:

-Changes in app.js in src folder
-Implemented a AJAX call to the API
-

### CODE REVIEW

**Comment by niftyy** [comment]
fix the indentation

**Comment by JLodha** [comment]
Sir please have a look

**Comment by niftyy** [comment]
good, now merge both the commits into a single commit.

**Comment by JLodha** [comment]
Sir after setting s for squash i am not able to move forward .
Please help

**Comment by niftyy** [comment]
https://www.youtube.com/watch?v=2E23I9PzplM

**Comment by sggts04** [comment]
.

**Comment by JLodha** [comment]
Sir have a look please

**Pull request merged**
