### PR TITLE
made code in MovieRow component beautiful

### LINKED ISSUE #47: Beautify code in MovieRow component

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__47__ 

Fixes #47

#### Short description of what this resolves:

made code in MovieRow component beautiful

#### Changes proposed in this pull request and/or Screenshots of changes:

beautiful

### CODE REVIEW

**Comment by niftyy** [comment]
screenshot and code don't match :/

**Comment by untrulynoxiusmj** [comment]
orig

**Comment by untrulynoxiusmj** [comment]
sir ,this is snip of  code

**Comment by niftyy** [comment]
reduce tab size to 4.

**Pull request merged**
