### PR TITLE
setup screenshot

### PR DESCRIPTION
**Pull request by smcri**
__7__
 

**Short description of what this resolves:**
Adds screenshot of setup

**Changes proposed in this pull request and/or Screenshots of changes:**

smcri-setup

### CODE REVIEW

**Comment by niftyy** [comment]
Screenshot is incorrect, please look at the other screenshots for reference and read the project setup instructions in the README. Also you have to follow the PR template in order to receive points.

**Comment by niftyy** [comment]
PR format is still incorrect. Please check the guidelines

**Comment by smcri** [comment]
Sir, can you please let me know my mistake?

**Comment by niftyy** [comment]
the first line of the PR description should be : [doubleunderscore]issuenumber[doubleunderscore]

**Comment by smcri** [comment]
First line edited

**Comment by niftyy** [comment]
your first line still is Edit:

**Comment by smcri** [comment]
Done.

**Pull request merged**
